global.disabled_tools = [
  "minecraft:wooden_shovel",
  "minecraft:wooden_pickaxe",
  "minecraft:wooden_axe",
  "minecraft:wooden_hoe",
  "minecraft:wooden_sword",
  "minecraft:stone_shovel",
  "minecraft:stone_pickaxe",
  "minecraft:stone_axe",
  "minecraft:stone_hoe",
  "minecraft:stone_sword",
  "minecraft:golden_shovel",
  "minecraft:golden_pickaxe",
  "minecraft:golden_axe",
  "minecraft:golden_hoe",
  "minecraft:golden_sword",
  "minecraft:iron_shovel",
  "minecraft:iron_pickaxe",
  "minecraft:iron_axe",
  "minecraft:iron_hoe",
  "minecraft:iron_sword",
  "minecraft:diamond_shovel",
  "minecraft:diamond_pickaxe",
  "minecraft:diamond_axe",
  "minecraft:diamond_hoe",
  "minecraft:diamond_sword",
  "minecraft:netherite_shovel",
  "minecraft:netherite_pickaxe",
  "minecraft:netherite_axe",
  "minecraft:netherite_hoe",
  "minecraft:netherite_sword",
  "ae2:certus_quartz_shovel",
  "ae2:certus_quartz_pickaxe",
  "ae2:certus_quartz_axe",
  "ae2:certus_quartz_hoe",
  "ae2:certus_quartz_sword",
  "ae2:nether_quartz_shovel",
  "ae2:nether_quartz_pickaxe",
  "ae2:nether_quartz_axe",
  "ae2:nether_quartz_hoe",
  "ae2:nether_quartz_sword",
  "ae2:fluix_shovel",
  "ae2:fluix_pickaxe",
  "ae2:fluix_axe",
  "ae2:fluix_hoe",
  "ae2:fluix_sword",
  "immersiveengineering:shovel_steel",
  "immersiveengineering:pickaxe_steel",
  "immersiveengineering:axe_steel",
  "immersiveengineering:hoe_steel",
  "immersiveengineering:sword_steel",

  "minecraft:leather_helmet",
  "minecraft:leather_chestplate",
  "minecraft:leather_leggings",
  "minecraft:leather_boots",
  "minecraft:chainmail_helmet",
  "minecraft:chainmail_chestplate",
  "minecraft:chainmail_leggings",
  "minecraft:chainmail_boots",
  "minecraft:iron_helmet",
  "minecraft:iron_chestplate",
  "minecraft:iron_leggings",
  "minecraft:iron_boots",
  "minecraft:golden_helmet",
  "minecraft:golden_chestplate",
  "minecraft:golden_leggings",
  "minecraft:golden_boots",
  "minecraft:diamond_helmet",
  "minecraft:diamond_chestplate",
  "minecraft:diamond_leggings",
  "minecraft:diamond_boots",
  "minecraft:netherite_helmet",
  "minecraft:netherite_chestplate",
  "minecraft:netherite_leggings",
  "minecraft:netherite_boots",
  "pneumaticcraft:compressed_iron_helmet",
  "pneumaticcraft:compressed_iron_chestplate",
  "pneumaticcraft:compressed_iron_leggings",
  "pneumaticcraft:compressed_iron_boots",
]

// ItemEvents.modification(event => {
//   global.disabled_tools.forEach(tool => event.modify(tool, item => {
//     item.maxDamage = 1
//     item.digSpeed = 0.1
//   }))
// });