ClientEvents.lang('en_us', (event) => {
    event.add("rite.wasteland.rubberwood_sapling", "Rite of Rubberwood")
    event.add("rite.wasteland.upgrade_inferium_seeds", "Inferium Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_coal_seeds", "Coal Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_copper_seeds", "Copper Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_dye_seeds", "Dye Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_iron_seeds", "Iron Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_nether_seeds", "Nether Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_skeleton_seeds", "Skeleton Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_zombie_seeds", "Zombie Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_air_seeds", "Air Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_earth_seeds", "Earth Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_fire_seeds", "Fire Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_water_seeds", "Water Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_experience_seeds", "Experience Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_lapis_lazuli_seeds", "Lapis Lazuli Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_nether_quartz_seeds", "Nether Quartz Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_redstone_seeds", "Redstone Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_spider_seeds", "Spider Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_tin_seeds", "Tin Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_blaze_seeds", "Blaze Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_creeper_seeds", "Creeper Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_diamond_seeds", "Diamond Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_emerald_seeds", "Emerald Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_end_seeds", "End Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_enderman_seeds", "Enderman Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_gold_seeds", "Gold Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_nickel_seeds", "Nickel Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_silver_seeds", "Silver Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_aluminum_seeds", "Aluminum Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_certus_quartz_seeds", "Certus Quartz Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_fluorite_seeds", "Fluorite Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_ghast_seeds", "Ghast Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_lead_seeds", "Lead Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_osmium_seeds", "Osmium Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_netherite_seeds", "Netherite Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_slime_seeds", "Slime Seeds Upgrade Rite")
    event.add("rite.wasteland.upgrade_wither_skeleton_seeds", "Wither Skeleton Seeds Upgrade Rite")
})